spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schedules
    username: scheduling_admin
    password: scheduling_pass

logging:
  level:
    com:
      work:
        scheduler: DEBUG
