spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schedules
    username: scheduling_admin
    password: scheduling_pass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
