spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/schedules
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com:
      work:
        scheduler: ${LOGGING_LEVEL}